name: Speedtest Benchmark
on:
  workflow_dispatch:

jobs:
  speedtest:
    name: Run Ookla Speedtest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg apt-transport-https speedtest-cli

      - name: Run speedtest and save results
        run: |
          speedtest
