name: Speedtest Benchmark
on:
  workflow_dispatch:

jobs:
  speedtest:
    name: Run Ookla Speedtest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg apt-transport-https
          
      - name: Add Ookla repository
        run: |
          curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash

      - name: Install Ookla Speedtest CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y speedtest

      - name: Run speedtest and save results
        run: |
          speedtest --accept-license --accept-gdpr
